/**
 * demo-data.ts
 * Canonical review corpus used by the live-feed simulator API.
 * Mirrors the seed data in scripts/seed-products.js — keep in sync.
 */

export const DEMO_REVIEWS: Record<string, string[]> = {
  smartphones: [
    "Battery life is great, easily lasts two days on moderate use.",
    "Camera takes stunning photos even in low light conditions.",
    "The display is gorgeous, vibrant colours and sharp text.",
    "Performance is buttery smooth, no lag whatsoever.",
    "Build quality feels premium, glass back looks sleek.",
    "Overheats badly during gaming, gets uncomfortable to hold.",
    "Battery drains to zero in under 8 hours on normal use.",
    "Camera app crashes frequently, loses photos mid-shoot.",
    "Speaker is tinny and very quiet compared to competitors.",
    "Fingerprint sensor is unreliable, fails 30% of the time.",
    "5G connectivity is fast and stable even in crowded areas.",
    "Software updates are timely and add genuinely useful features.",
    "Night mode photography is exceptional, rivals DSLRs.",
    "Charging speed is incredibly fast, 80% in 30 minutes.",
    "The haptic feedback is satisfying and very precise.",
    "Screen protector included in the box is a nice touch.",
    "GPS lock is near-instant and stays accurate all day.",
    "Bluetooth range is excellent, no drops up to 15m.",
    "The always-on display barely impacts battery, well optimised.",
    "Face unlock works in complete darkness, impressive.",
    "Bloatware is minimal, clean out-of-box experience.",
    "Call quality is crystal clear even in noisy environments.",
    "Macro lens produces beautiful close-up shots.",
    "Wireless charging works through thick cases, very convenient.",
    "RAM management is poor, apps reload constantly in background.",
    "Display has a green tint at low brightness, very distracting.",
    "Wi-Fi drops frequently on 5GHz band, intermittent issue.",
    "SIM tray is very difficult to open, flimsy ejector pin.",
    "Software feels half-baked, many settings are buried.",
    "Screen scratched within a week despite careful use.",
  ],
  earbuds: [
    "Sound quality is absolutely incredible, deep bass and crisp highs.",
    "ANC works brilliantly, completely blocks out metro noise.",
    "Battery lasts 8 hours on a single charge, very impressive.",
    "Pairing is seamless with my phone, connected instantly.",
    "The fit is snug and comfortable even during workouts.",
    "Microphone picks up my voice clearly on calls.",
    "Sound quality is decent but bass is a bit weak for my taste.",
    "ANC doesn't block wind noise very well outdoors.",
    "Battery drains faster than advertised, barely 5 hours.",
    "Pairing with multiple devices is a pain, keeps dropping.",
    "The ear tips hurt after about an hour of use.",
    "Call quality is muffled, people on calls can barely hear me.",
    "Absolutely love the transparency mode, very natural.",
    "Charging case charges the buds 3 times, great for travel.",
    "The touch controls are very responsive and customizable.",
    "Sound leakage is noticeable at high volumes.",
    "Water resistance is solid, survived a heavy rain session.",
    "The companion app is intuitive and has good EQ options.",
    "Bass is too boosted, muddy for detailed music listening.",
    "Keeps falling out of my ears during runs.",
    "ANC level is adjustable which is a great feature.",
    "Latency is noticeable when watching videos, lip sync is off.",
    "Sound stage is wide and very immersive for the price.",
    "The carrying case feels premium and charges wirelessly.",
    "Right earbud stopped working after 2 months. Terrible quality.",
    "Very lightweight, you forget you're wearing them.",
    "Noise cancellation doesn't block low hum of AC units.",
    "The buds charge to 100% in just 45 minutes.",
    "Audio codec support is limited, no LDAC or aptX.",
    "Best earbuds I've ever owned in this price range.",
  ],
  laptops: [
    "Battery life is phenomenal, lasts over 12 hours on a charge.",
    "Display is stunning, 2K resolution with excellent color accuracy.",
    "The keyboard has perfect travel and tactile feedback.",
    "Performance is blazing fast, handles heavy multitasking easily.",
    "Build quality feels premium, all-metal chassis is solid.",
    "Thermals are excellent, stays cool even under full load.",
    "Battery lasts only 5 hours under real-world usage.",
    "Display has a washed out color profile out of the box.",
    "Keyboard has flex and the trackpad is unresponsive sometimes.",
    "It throttles badly when running large ML models.",
    "The chassis creaks when you pick it up, cheap feeling.",
    "Fan noise is extremely loud when doing any heavy task.",
    "Stunning OLED display, perfect blacks and vibrant colors.",
    "Charges to 80% in just 30 minutes with fast charging.",
    "RAM and storage are not upgradeable, makes it feel dated.",
    "The trackpad is smooth and supports all multi-touch gestures.",
    "Speakers are surprisingly loud and clear for a thin laptop.",
    "Wifi connectivity drops frequently in crowded networks.",
    "The hinge wobbles when you type, very distracting.",
    "Boot time is under 10 seconds, incredibly fast startup.",
    "Webcam quality is terrible for video calls.",
    "Port selection is good: 2 USB-A, 2 USB-C, HDMI.",
    "Gets uncomfortably hot on the bottom during gaming.",
    "Comes with too much bloatware pre-installed.",
    "The build quality is exceptional, no flex anywhere.",
    "Weight is under 1.2kg, best lightweight laptop I've owned.",
    "Battery drains to zero in sleep mode overnight.",
    "Screen brightness is insufficient in direct sunlight.",
    "Performance benchmarks are excellent for the price point.",
    "Cooling vents are placed awkwardly and get blocked on lap.",
  ],
  geyser: [
    "Water heats up very quickly, ready in under 10 minutes.",
    "Energy efficiency is impressive, noticed a drop in electricity bill.",
    "Safety thermostat works perfectly, never overheats.",
    "Build quality is solid, stainless steel tank feels durable.",
    "Installation was straightforward and took less than an hour.",
    "Makes a loud popping noise when heating, very annoying.",
    "Water takes 25 minutes to heat up, too slow for mornings.",
    "Electricity consumption is very high, bill shot up this month.",
    "Thermostat failed after 3 months, water was scalding hot.",
    "The casing has already started rusting near the inlet.",
    "Reliable hot water supply even in cold winters, love it.",
    "Temperature control dial is very precise and easy to use.",
    "The pilot light keeps going out, frustrating to relight.",
    "Heating element failed within 6 months, poor component quality.",
    "Anti-siphon valve works correctly, great safety feature.",
    "Excellent insulation, water stays hot for over 4 hours.",
    "The pressure relief valve drips constantly, must be defective.",
    "Warranty service was excellent, technician arrived same day.",
    "The outer body gets extremely hot to touch, safety hazard.",
    "Energy star rated, very efficient for a glass-lined tank.",
    "Makes grinding noise during operation, concerning sound.",
    "The anode rod is replaceable which extends the product life.",
    "Bracket mounting is wobbly, not secure on the wall.",
    "Hot water supply is consistent throughout the day.",
    "Sediment build-up clogged the outlet within 4 months.",
    "Temperature uniformity is excellent from first to last bucket.",
    "The digital display for temperature setting is very helpful.",
    "Paint on the body started peeling within weeks of installation.",
    "Outstanding performance, zero complaints after one year of use.",
    "Takes too long to recover between back-to-back showers.",
  ],
  refrigerator: [
    "Cooling performance is outstanding, vegetables stay fresh for weeks.",
    "Very energy efficient, consumes less than 2 units per day.",
    "Compressor is whisper quiet, can barely hear it running.",
    "Build quality is excellent, robust shelves and sturdy doors.",
    "Ice maker works flawlessly, produces ice very quickly.",
    "Takes over 3 hours to reach set temperature from warm start.",
    "Energy consumption is higher than the rated specification.",
    "Compressor is extremely loud at night, disturbs sleep.",
    "Door seal worn out in less than a year, warm spots inside.",
    "Ice maker jams frequently and dispenser makes cracking noises.",
    "Freezer maintains an even -18°C consistently, very reliable.",
    "The LED interior lighting is bright and coverage is excellent.",
    "Frost build-up in freezer every week despite auto-defrost claim.",
    "Water dispenser leaks slowly from the fitting, constant drip.",
    "Vegetable crisper drawer humidity control works perfectly.",
    "The door bins are too shallow and bottles keep falling.",
    "Digital temperature display is easy to read and set precisely.",
    "Fridge runs warm at the back, dairy spoils faster than expected.",
    "The handles feel cheap and plastic, don't match the price point.",
    "Impressive capacity for the compact footprint, very spacious inside.",
    "Alarm for open door is loud and triggers even for short durations.",
    "Adjustable shelving system accommodates tall items very well.",
    "Paint on the exterior scratches easily, shows marks quickly.",
    "Delivered with a dent on the door, poor packaging protection.",
    "Freezer door doesn't seal completely, frost everywhere.",
    "Smart diagnostics app helps identify issues before they occur.",
    "Runs continuously without cycling off, must have a fault.",
    "Temperature fluctuates 3-4 degrees throughout the day.",
    "The glass shelves are tempered and very easy to clean.",
    "Five years and the compressor is still going strong.",
  ],
  "microwave-oven": [
    "Heats food very evenly, no cold spots even in dense meals.",
    "Timer and power level controls are intuitive and responsive.",
    "The turntable rotates smoothly and distributes heat well.",
    "Pre-programmed cooking modes work accurately for most foods.",
    "Door seal is tight, no microwave leakage detected.",
    "Heats unevenly, edges burn while center stays cold.",
    "Controls are confusing, the manual is poorly written.",
    "Turntable stopped rotating after just two months of use.",
    "Auto-cook programs are wildly inaccurate for most dishes.",
    "Door latch broken after repeated use, safety concern.",
    "Convection mode bakes bread perfectly, crispy crust every time.",
    "Interior is very spacious, fits a large casserole dish easily.",
    "The fan continues running for 5 minutes after cooking, very odd.",
    "Paint inside the cavity is peeling and ending up in food.",
    "Display brightness is poor, cannot read in daylight.",
    "Defrost function is excellent, defrosts without cooking edges.",
    "Touch pad is very responsive and easy to program.",
    "Sparking occurred inside on first use, extremely dangerous.",
    "Energy consumption per cycle is very efficient and low.",
    "Door handle broke off completely within three months of use.",
    "Grill function creates a perfect golden crust on food.",
    "The magnetron emits a humming noise during high power use.",
    "Interior light stays on after door closes, must be a defect.",
    "Timer accuracy is perfect, consistent to the second.",
    "Plastic interior smells when heating food, chemical odour.",
    "Child lock feature works well, prevents accidental operation.",
    "Steam cooking accessory included works better than expected.",
    "Exterior gets very hot during operation, risk of burns.",
    "Consistent performance across all power levels is impressive.",
    "Touchpad stopped working after a minor water splash.",
  ],
};
